### PR TITLE
Don't combine distribution if count == 0

### PR DESCRIPTION
**Pull request by mitchellwrosen**
This is one possible solution to #24.

### CODE REVIEW

**Comment by 23Skidoo** [comment]
I'm not very familiar with this bit of `ekg`, would be nice if @tibbe could take a look.

**Comment by mitchellwrosen** [comment]
Bump, thoughts @tibbe? :)

**Comment by 23Skidoo** [comment]
@tibbe thinks it's good to go, merging.

**Comment by 23Skidoo** [comment]
Merged, thanks!

**Comment by pepeiborra** [comment]
I don't know how, but this change led to a 100% reproducible lock-up in one of our EKG enabled services at work (Strats SCB). This is using 8.4.4. We forked ekg-core while preparing for an upgrade to 8.6.2. 
Unfortunately I cannot provide a repro for obvious reasons.

**Comment by mitchellwrosen** [comment]
Ouch. I'm sorry about that @pepeiborra. Can you provide any more information?

**Comment by 23Skidoo** [comment]
Reverted.

**Comment by adamse** [comment]
Possible diagnosis: 

The quick exit path in `hs_distrib_add_n` added here doesn't release the lock so any subsequent calls to `hs_distrib_add_n` with the same `b` param will wait forever in `hs_lock(&b->lock)`.

**Comment by mitchellwrosen** [comment]
@nh2 Right, that's the obvious bug. I apologize :(

**Comment by nh2** [comment]
@mitchellwrosen Can happen! It seems `ekg` needs better tests if a simple change like this can take down Standard Chartered's upgrade at runtime.

**Pull request merged**
