### PR TITLE
Support GHC 8.10

### PR DESCRIPTION
**Pull request by jberryman**

### CODE REVIEW

**Comment by 23Skidoo** [comment]
Merged, thanks!

**Comment by 23Skidoo** [comment]
Grrr, apparently this broke the build with GHC < 7.10.

**Comment by jberryman** [comment]
If you can configure travis to run on PRs I can try to get it working. But I don't have 7.10 installed locally.

**Comment by 23Skidoo** [comment]
It [seems to be running on PRs](https://travis-ci.org/github/tibbe/ekg-core/pull_requests), just not publishing status for some reason.

**Comment by jberryman** [comment]
Thanks, it looks like it failed due to "not in scope `<$>`", which would have been from some prior commit (or maybe older GHCs never worked). Dropping older GHCs probably would make sense imo, if no one has noticed

**Comment by 23Skidoo** [comment]
Oh, it did work before this PR was merged, you can check by clicking on "Build History".

**Comment by jberryman** [comment]
Oh sorry, looking cross-eyed at the diff. Will open a new PR in a sec, reverting removing that import

**Comment by 23Skidoo** [comment]
I made a Hackage revision allowing `ekg-core-0.1.1.7` to be build with 8.10.

**Pull request merged**
